 spring.application.name=healhub
 spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalRecord
spring.datasource.username=postgres
spring.datasource.password=Rishu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
